version: "3.8"
services:

  checkard:
    build: ./
    container_name: checkard
    volumes:
      - ./:/usr/src/app
      - checkard_node_modules:/usr/src/app/node_modules


volumes:
  checkard_node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/node_modules